/*
 * File: app/store/ExpenseStore.js
 * Date: Tue Oct 25 2011 05:28:53 GMT-0700 (PDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ExpenseStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ExpenseStore',
            proxy: {
                type: 'ajax',
                url: 'data/getExpenses.json',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'actualDate'
                },
                {
                    name: 'submitDate'
                },
                {
                    name: 'category'
                },
                {
                    name: 'amount'
                }
            ]
        }, cfg)]);
    }
});