/*
 * File: app/view/ExpenseTracker.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.ExpenseTracker', {
    extend: 'MyApp.view.ui.ExpenseTracker',
    alias: 'widget.expensetracker',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    },

    onComboboxChange: function(field, newValue, oldValue, options) {
        var activeItem = 0,
        expenseStore = Ext.StoreMgr.lookup('ExpenseStore'),
        chartCt = this.down('#chartCt');
                                                    
        expenseStore.clearFilter();
        if (newValue) {
            activeItem = 1;
            expenseStore.filter('category', newValue);
        }
        chartCt.getLayout().setActiveItem(activeItem);
    }

});