/*
 * File: app/view/ExpensePieChart.js
 * Date: Tue Oct 25 2011 05:35:09 GMT-0700 (PDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.ExpensePieChart', {
    extend: 'MyApp.view.ui.ExpensePieChart',
    alias: 'widget.expensepiechart',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }

});