/*
 * File: app/view/ExpenseGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.ExpenseGrid', {
    extend: 'MyApp.view.ui.ExpenseGrid',
    alias: 'widget.expensegrid',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }

});