/*
 * File: app/view/ui/ExpensePieChart.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.ExpensePieChart', {
    extend: 'Ext.chart.Chart',

    height: 250,
    width: 400,
    animate: true,
    insetPadding: 20,
    store: 'ExpenseStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            series: [
                {
                    type: 'pie',
                    label: {
                        field: 'name',
                        display: 'rotate',
                        contrast: true,
                        font: '12px Arial'
                    },
                    showInLegend: true,
                    angleField: 'amount'
                }
            ]
        });

        me.callParent(arguments);
    }

});