/*
 * File: app/view/ui/Viewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.Viewport', {
    extend: 'Ext.container.Viewport',
    requires: [
        'MyApp.view.ExpenseTracker'
    ],


    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'expensetracker'
                }
            ]
        });

        me.callParent(arguments);
    }

});