/*
 * File: app/store/base/CategoryStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you save.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.base.CategoryStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CategoryStore',
            proxy: {
                type: 'ajax',
                url: 'data/getCategories.json',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'category'
                }
            ]
        }, cfg)]);
    }
});